// <auto-generated />
using System;
using CinemaBookingAPI_SOA_CA2_JIanfengHan.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaBookingAPI_SOA_CA2_JIanfengHan.Migrations
{
    [DbContext(typeof(CinemaContext))]
    partial class CinemaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("CinemaBookingAPI_SOA_CA2_JIanfengHan.Models.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("ScreeningId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SeatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.HasIndex("ScreeningId", "SeatId")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CinemaBookingAPI_SOA_CA2_JIanfengHan.Models.Movie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("CinemaBookingAPI_SOA_CA2_JIanfengHan.Models.Screening", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HallNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Screenings");
                });

            modelBuilder.Entity("CinemaBookingAPI_SOA_CA2_JIanfengHan.Models.Seat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HallNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            HallNumber = 1,
                            Row = "A",
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 2L,
                            HallNumber = 1,
                            Row = "A",
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 3L,
                            HallNumber = 1,
                            Row = "A",
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 4L,
                            HallNumber = 1,
                            Row = "B",
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 5L,
                            HallNumber = 1,
                            Row = "B",
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 6L,
                            HallNumber = 1,
                            Row = "B",
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 7L,
                            HallNumber = 1,
                            Row = "C",
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 8L,
                            HallNumber = 1,
                            Row = "C",
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 9L,
                            HallNumber = 1,
                            Row = "C",
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 10L,
                            HallNumber = 1,
                            Row = "D",
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 11L,
                            HallNumber = 1,
                            Row = "D",
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 12L,
                            HallNumber = 1,
                            Row = "D",
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 13L,
                            HallNumber = 1,
                            Row = "D",
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 14L,
                            HallNumber = 2,
                            Row = "A",
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 15L,
                            HallNumber = 2,
                            Row = "A",
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 16L,
                            HallNumber = 2,
                            Row = "A",
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 17L,
                            HallNumber = 2,
                            Row = "B",
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 18L,
                            HallNumber = 2,
                            Row = "B",
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 19L,
                            HallNumber = 2,
                            Row = "B",
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 20L,
                            HallNumber = 2,
                            Row = "C",
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 21L,
                            HallNumber = 2,
                            Row = "C",
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 22L,
                            HallNumber = 2,
                            Row = "C",
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 23L,
                            HallNumber = 2,
                            Row = "C",
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 24L,
                            HallNumber = 2,
                            Row = "D",
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 25L,
                            HallNumber = 2,
                            Row = "D",
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 26L,
                            HallNumber = 2,
                            Row = "D",
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 27L,
                            HallNumber = 2,
                            Row = "D",
                            SeatNumber = 4
                        });
                });

            modelBuilder.Entity("CinemaBookingAPI_SOA_CA2_JIanfengHan.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CinemaBookingAPI_SOA_CA2_JIanfengHan.Models.Booking", b =>
                {
                    b.HasOne("CinemaBookingAPI_SOA_CA2_JIanfengHan.Models.Screening", "Screening")
                        .WithMany("Bookings")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBookingAPI_SOA_CA2_JIanfengHan.Models.Seat", "Seat")
                        .WithMany("Bookings")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBookingAPI_SOA_CA2_JIanfengHan.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screening");

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaBookingAPI_SOA_CA2_JIanfengHan.Models.Screening", b =>
                {
                    b.HasOne("CinemaBookingAPI_SOA_CA2_JIanfengHan.Models.Movie", "Movie")
                        .WithMany("Screenings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBookingAPI_SOA_CA2_JIanfengHan.Models.Movie", b =>
                {
                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("CinemaBookingAPI_SOA_CA2_JIanfengHan.Models.Screening", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CinemaBookingAPI_SOA_CA2_JIanfengHan.Models.Seat", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CinemaBookingAPI_SOA_CA2_JIanfengHan.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
